/**
 * Seed data for warehouses in Ethiopian cities
 * Creates multiple warehouse origins for GPS-tracked deliveries
 */

export const WAREHOUSE_SEED_DATA = [
  {
    name: 'Minalesh Addis Ababa Central Warehouse',
    code: 'AA-CENTRAL',
    address: 'Bole Road, near Edna Mall',
    city: 'Addis Ababa',
    region: 'Addis Ababa',
    country: 'Ethiopia',
    postalCode: '1000',
    latitude: 9.0192,
    longitude: 38.7525,
    phone: '+251911000001',
    email: 'warehouse.aa@minalesh.com',
    managerName: 'Abebe Kebede',
    capacity: 10000,
    operatingHours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '09:00', close: '15:00' },
      sunday: { open: 'closed', close: 'closed' },
    },
    isActive: true,
    isPrimary: true, // Main warehouse
  },
  {
    name: 'Minalesh Addis Ababa Merkato Warehouse',
    code: 'AA-MERKATO',
    address: 'Merkato Shopping District',
    city: 'Addis Ababa',
    region: 'Addis Ababa',
    country: 'Ethiopia',
    postalCode: '1000',
    latitude: 9.0320,
    longitude: 38.7469,
    phone: '+251911000002',
    email: 'warehouse.merkato@minalesh.com',
    managerName: 'Tigist Haile',
    capacity: 5000,
    operatingHours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '09:00', close: '15:00' },
      sunday: { open: 'closed', close: 'closed' },
    },
    isActive: true,
    isPrimary: false,
  },
  {
    name: 'Minalesh Dire Dawa Warehouse',
    code: 'DD-01',
    address: 'Kezira, near Railway Station',
    city: 'Dire Dawa',
    region: 'Dire Dawa',
    country: 'Ethiopia',
    postalCode: '1100',
    latitude: 9.6008,
    longitude: 41.8661,
    phone: '+251911000003',
    email: 'warehouse.dd@minalesh.com',
    managerName: 'Mohammed Ali',
    capacity: 3000,
    operatingHours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '09:00', close: '15:00' },
      sunday: { open: 'closed', close: 'closed' },
    },
    isActive: true,
    isPrimary: false,
  },
  {
    name: 'Minalesh Hawassa Warehouse',
    code: 'HW-01',
    address: 'Piassa, near Lake Hawassa',
    city: 'Hawassa',
    region: 'Sidama',
    country: 'Ethiopia',
    postalCode: '1560',
    latitude: 7.0621,
    longitude: 38.4769,
    phone: '+251911000004',
    email: 'warehouse.hw@minalesh.com',
    managerName: 'Dawit Tesfaye',
    capacity: 2000,
    operatingHours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '09:00', close: '15:00' },
      sunday: { open: 'closed', close: 'closed' },
    },
    isActive: true,
    isPrimary: false,
  },
  {
    name: 'Minalesh Bahir Dar Warehouse',
    code: 'BD-01',
    address: 'Blue Nile Avenue, near Tana Hotel',
    city: 'Bahir Dar',
    region: 'Amhara',
    country: 'Ethiopia',
    postalCode: '6000',
    latitude: 11.5948,
    longitude: 37.3615,
    phone: '+251911000005',
    email: 'warehouse.bd@minalesh.com',
    managerName: 'Almaz Worku',
    capacity: 2500,
    operatingHours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '09:00', close: '15:00' },
      sunday: { open: 'closed', close: 'closed' },
    },
    isActive: true,
    isPrimary: false,
  },
  {
    name: 'Minalesh Mekelle Warehouse',
    code: 'MK-01',
    address: 'Hawelti Semaetat, near Airport',
    city: 'Mekelle',
    region: 'Tigray',
    country: 'Ethiopia',
    postalCode: '7000',
    latitude: 13.4967,
    longitude: 39.4753,
    phone: '+251911000006',
    email: 'warehouse.mk@minalesh.com',
    managerName: 'Hailay Gebrehiwot',
    capacity: 2000,
    operatingHours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '09:00', close: '15:00' },
      sunday: { open: 'closed', close: 'closed' },
    },
    isActive: true,
    isPrimary: false,
  },
];
