export {
  GoogleAnalytics,
  pageview,
  trackEvent,
  trackViewProduct,
  trackAddToCart,
  trackRemoveFromCart,
  trackViewCart,
  trackBeginCheckout,
  trackAddShippingInfo,
  trackAddPaymentInfo,
  trackPurchase,
  trackRefund,
  trackSearch,
  trackSignUp,
  trackLogin,
  trackAddToWishlist,
  trackShare,
  trackPriceAlertCreated,
  trackSavedSearchCreated,
} from './GoogleAnalytics';
